import json

def convert_to_netscape(json_file, output_file):
    with open(json_file, 'r') as f:
        cookies = json.load(f)

    with open(output_file, 'w') as f:
        f.write("# Netscape HTTP Cookie File\n")
        f.write("# This file was generated by convert_cookies.py\n\n")
        for cookie in cookies:
            domain = cookie['domain']
            flag = "TRUE" if cookie.get('hostOnly', False) else "FALSE"
            path = cookie.get('path', '/')
            secure = "TRUE" if cookie.get('secure', False) else "FALSE"
            expires = int(cookie.get('expirationDate', 0))
            name = cookie['name']
            value = cookie['value']
            f.write(f"{domain}\t{flag}\t{path}\t{secure}\t{expires}\t{name}\t{value}\n")

if __name__ == "__main__":
    convert_to_netscape(
        "/home/rustambek/cookies_temp.json",
        "/home/rustambek/PycharmProjects/MusiqaBot/cookies.txt"
    )